import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';
import LoginBtn from './loginBtn';
import LogoutBtn from './logoutBtn';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/pages/api/auth/[...nextauth]';
import DarkMode from './darkMode';
import { cookies } from 'next/headers';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);
  let cookie = cookies().get('mode');

  // if (session) {
  //   console.log(session.user.name);
  // }
  return (
    <html lang='en'>
      <body
        className={
          cookie != undefined && cookie.value == 'dark'
            ? `${inter.className} dark-mode`
            : inter.className
        }
      >
        <div className='navbar'>
          <Link href='/' className='logo'>
            Appleforum
          </Link>
          <Link href='/list'>List</Link>
          {session ? (
            <>
              <span>안녕하세요, {session.user.name}님 </span>
              <LogoutBtn></LogoutBtn>
            </>
          ) : (
            <>
              <LoginBtn></LoginBtn>
              <Link href='/register'>
                <button>회원가입</button>
              </Link>
            </>
          )}
          <DarkMode />
        </div>
        {children}
      </body>
    </html>
  );
}
